apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana-image-renderer
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 7.4.3
  name: grafana-image-renderer-svc
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8081
    targetPort: http
  selector:
    app.kubernetes.io/component: grafana-image-renderer
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/part-of: kube-prometheus
